### PR TITLE
fix: always use English for TimeAgo

### LINKED ISSUE #893: Why messages timestamps are negative
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.

**You are setting up gotify in**
- [ ] Gotify server: kubernetes cluster
- [ ] Gotify client: raspberry pi/debian 13 and macbook/macos 26

**Describe your problem**

I have deployed gotify server in my kubernetes cluster, with a simple helm chart.
Chart is using gotify default configuration, only admin name/pass are updated at first start.

I have created two apps in gotify, one for my raspberry pi, one for my macbook.
I have installed gotify-cli on my my raspberry pi, but not on my macbook.

I have sent messages from raspberry and macbook to gotify-server.
Messages are displayed with negative timestamps:

Image

This is weird, I don't understand why timestamps are displayed like this.

Server, raspberry pi and macbook are all using timesync/ntp and "Europe/Paris" as timezone.

Do someone what is happening here?

**Any errors, logs, or other information that might help us identify your problem**

No log available.

### PR DESCRIPTION
**Pull request by eternal-flame-AD**
Fixes #893 

Also lifted the config out to a global object per the docs for performance.

### CODE REVIEW

File: ui/src/common/TimeAgoConfig.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import {Formatter} from 'react-timeago';
+import {makeIntlFormatter} from 'react-timeago/defaultFormatter';
+
+export const TimeAgoFormatter: Map<'long' | 'narrow', Formatter> = new Map([
+    ['long', makeIntlFormatter({style: 'long', locale: 'en'})],
+    ['narrow', makeIntlFormatter({style: 'narrow', locale: 'en'})],
+]);
```
Comment (jmattheis) [inline ui/src/common/TimeAgoConfig.ts]: In this case a normal record should be enough. This then can be accessed with TimeAgoFormatter.long
```suggestion
export const TimeAgoFormatter: Record<'long' | 'narrow', Formatter> = {
    long: makeIntlFormatter({style: 'long', locale: 'en'}),
    narrow: makeIntlFormatter({style: 'narrow', locale: 'en'}),
};
```

File: ui/src/common/TimeAgoConfig.ts [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import {Formatter} from 'react-timeago';
+import {makeIntlFormatter} from 'react-timeago/defaultFormatter';
+
+export const TimeAgoFormatter: Map<'long' | 'narrow', Formatter> = new Map([
```
Comment (jmattheis) [inline ui/src/common/TimeAgoConfig.ts]: If there is only one export in a file, the file should be named exactly like the export.

File: ui/src/typedef/react-timeago.d.ts [hunk 3]
```diff
@@ -3,6 +3,7 @@ declare module 'react-timeago' {
 
     export type FormatterOptions = {
         style?: 'long' | 'short' | 'narrow';
+        locale?: void | string;
```
Comment (jmattheis) [inline ui/src/typedef/react-timeago.d.ts]:
```suggestion
        locale?: string;
```

**Review by jmattheis — CHANGES_REQUESTED** [review]

File: ui/src/typedef/react-timeago.d.ts (hunk 3 above)
Comment (eternal-flame-AD) [reply ui/src/typedef/react-timeago.d.ts]: I copied this verbatim from upstream, but I agree this doesn't have to be this confusing...

https://github.com/nmn/react-timeago/blob/8883dba903c47d6e93e03c4f5efaef60c94ccad4/src/defaultFormatter.js#L17

Comment (jmattheis) [reply ui/src/typedef/react-timeago.d.ts]: timeago is using [flow](https://flow.org/en/docs/types/primitives/). This is a typesystem for JavaScript. We use TypeScript, and according to [the docs](https://flow.org/en/docs/types/primitives/) `void` is `undefined` and in typescript this is already covered by `?:`.
