### PR TITLE
Fix overlapping audio notifications for high-priority messages

### LINKED ISSUE #850: Throttle notification sound in web UI
Sometime I get a massive flood of notifications. For example I rename a season folder in jellyfin and get a flood of delete and added notifications at once.

This comes with an annoying flood of notification sounds trying to play simultaneously.

A simple solution would be to throttle the notification sound. Maybe no more than 1 sound per 2 seconds?

### PR DESCRIPTION
**Pull request by LaurenceJJones**
fix #850

- Add audioNotification utility to manage single Audio instance reuse
- Debounce audio playback with 300ms cooldown after playback ends
- Skip playback if audio is currently playing or in cooldown window
- Replace per-message Audio creation with shared instance in reactions.ts

### CODE REVIEW

File: ui/src/audioNotification.ts [hunk 1]
```diff
@@ -1,19 +1,22 @@
 let audioInstance: HTMLAudioElement | null = null;
-let isPlaying = false;
 let cooldownEndTime = 0;
```
Comment (jmattheis) [inline ui/src/audioNotification.ts]: I dislike global state as we can get weird side-effects from this. The caching state should be local in some function, or be inside the statemanagement.

File: ui/src/audioNotification.ts [hunk 2]
```diff
@@ -1,19 +1,22 @@
...
     const now = Date.now();
 
-    // Skip if currently playing or in cooldown
-    if (isPlaying || now < cooldownEndTime) {
+    // Skip if in cooldown
+    if (now < cooldownEndTime) {
+        return;
+    }
+
+    // Check if audio is currently playing
```
Comment (jmattheis) [inline ui/src/audioNotification.ts]: With the comments this looks AI generated, and the solution seems overly complicated to be reusable by passing `src` as parameter.

If we'd call this method with different `src`, only the last one is cached, and the throttling would be global, but yeah, this complexity isn't needed now.

File: ui/src/audioNotification.ts [hunk 3]
```diff
@@ -23,15 +26,15 @@ export function playNotificationAudio(src: string = DEFAULT_SRC): void {
         audioInstance.addEventListener('ended', handleAudioEnd);
```
Comment (jmattheis) [inline ui/src/audioNotification.ts]: Given that we know how long the audio notification is, we can omit this dynamic handling and define a countdown that's audio duration + cooldown. This will make this simpler.

**Review by jmattheis — APPROVED** [review]

File: ui/src/audioNotification.ts (hunk 3 above)
Comment (LaurenceJJones) [reply ui/src/audioNotification.ts]: 100% makes sense

File: ui/src/audioNotification.ts (hunk 2 above)
Comment (LaurenceJJones) [reply ui/src/audioNotification.ts]: Yes, claude was used to scaffold and I thought, hmmm yeah an outside component could be good if we plan to make apps have customized sounds. However, your right the functionality isnt there and plus I dont know if its ever planned so extracting a function is just unnecessary.
